### ISSUE TITLE
Bugs with dragging pre-created BlendSpace extensions into Animation Module

### ISSUE THREAD

**Issue by DaltonFox** [Avindr/MxM-IssueTracking#119]
**Bugs:**
- If `Type: Scatter Y` is set before adding the Blend Space to an Animation Module it is reset to `Type: Scatter X` and has to be opened from the Animation Module and switched back to `Type: Scatter Y` manually.

- Once a Blend Space is added to Animation Module it no longer updates from the source Blend Space that was created in the asset folder. You must open the Blend Space directly from the module after adding it. If this is intentional and a clone is being made instead of using it as a reference it seems to defeat the point of modularity in making them extensions for re-use.

**Instructions:**
Make a new Blend Space with `Create->MxM->Extensions->BlendSpace`. After setting it up with `Type: Scatter Y`, and then drag it into an Animation Module. Open the Blend Space from the Animation Module and notice `Type: Scatter Y` has reset to `Type: Scatter X`. Make an edit to the Blend Space outside of the Animation Module and notice it does not update within the module.

**Unity Version:** 
Unity 2020.3.41f
MxM 2.2.9

**Comment by Avindr** [comment]
Thanks for the feedback/report. I'll look into it.

**Comment by Avindr** [comment]
I'm unable to reproduce the issue in Unity 2020.3LTS. When I add a blend space to a Pre-Processor or Animation Module, the scatter space type seems to copy over fine.

Regarding the modularity issue. You are correct, the blend space is being copied into the AnimModule or Pre-Processor. This is currently as intended as standalone blend spaces were created only recently to enable blend spaces being used on layers above the motion matching layer. They were not originally intended for modularity. In essence this is a legacy issue because it never used to be possible to create standalone blend spaces at all.

I may make it work on references in the future but there is quite a bit of work to do to enable that as it is not how it was originally setup.
