### ISSUE TITLE
Allow us to name anims in the animation module - Improvement

### ISSUE THREAD

**Issue by Craigjw** [Avindr/MxM-IssueTracking#126]
The animations module allows us to add animations to use, the naming of these is predetermined by the animation name, this animation name can sometime be awkward to inspect.  In particular, the blend spaces will be named by the first animation that we use to create the blend tree, if we have multiple blend trees, each named with the same name, these can become confusing.

I'm not too concerned about the individual animations, as we can rename the animations themselves to more appropriate names, which helps identify them in the animation module,, however the blend spaces can be particularly confusing if there is multiple blend spaces with the same name.

**Comment by Avindr** [comment]
Hi,

Yes this is something I'm aware of and want to fix soon. It was actually planned for the last update but due to circumstances it didn't make the cut. I'll probably fit it in with the next udpate.

Cheers

**Comment by Avindr** [comment]
It does not seem possible to change the names of embedded assets. No matter what I try the name change does not persist. Therefore instead of changing the asset name, the composites and blend spaces can now be labelled. 

Simply set the name of the composite or blend space in the Name: section on the top left of the MxMAnimConfig window and the label in the lists will be updated to match.

![image](https://user-images.githubusercontent.com/29056263/142797462-b01b9446-9621-4b36-93e4-506c7997aad8.png)
![image](https://user-images.githubusercontent.com/29056263/142797495-c61f6387-4ac4-4149-88df-0c7efbb202da.png)

This will be included with update 2.10 coming soon.

**Comment by Craigjw** [comment]
That will be fine, thank you for that change.
