### ISSUE TITLE
Possible gravity bug in root motion applicator

### ISSUE THREAD

**Issue by andthenwhat** [Avindr/MxM-IssueTracking#155]
MxMRootMotionApplicator.cs:119
is currently 
```
                        moveDelta.y = (m_charController.Velocity.y +
                            Physics.gravity.y * a_deltaTime) * a_deltaTime;
```
but I think I think velocity.y needs to be scaled by a_deltaTime as well (since velocity is in m/s):
```
                        moveDelta.y = (m_charController.Velocity.y*a_deltaTime +
                            Physics.gravity.y * a_deltaTime) * a_deltaTime;
```
the player was dropping like a rock whenever I went off a platform, and I think the latter is right.  I searched issues and discord for references to this and didn't see any, but apologies if this is a duplicate.

**Comment by Avindr** [comment]
So Velocity it m/s,
Acceleration is m/s^2

So in the brackets we only multiply the acceleration by delta time to turn it into a velocity increment so that we can add it to the current velocity.

New Velocity = m/s + m/s^2 * s = m/s + m/s = m/s

Then we multiply the New Velocity by delta time again to get the displacement:   m/s * s = m

So after looking at it, the first one does seem correct to me still. However, if the character is dropping like a rock there must be some other issue which I haven't seen myself. I'll investigate.
