### ISSUE TITLE
Event Definition does not support EventNamingModule for event names in Editor

### ISSUE THREAD

**Issue by freyzor** [Avindr/MxM-IssueTracking#173]
When creating Event Definition you need to reference processed anim data to be able to reference named events.  This requires you to first re-process the anim data when adding new event names to be able to reference them when editing the Event Definition.  There is no option to use an EventNamingModule, which IMO is a much better way to define the names and would allow direct access to defined names as soon as they are added with out any reprocessing.   You could argue the that you should drop the ref anim data from the event definition in favor of using the EventNamingModule but I suppose it does not hurt to support it still as it already works.

**Comment by Avindr** [comment]
Yes this is a legacy feature from before event naming modules existed and event names lived directly on the animdata. 

I will add an EventNamingModule option to the event definitions to allow event names to update without re-processing but will keep the TargetAnimData in place in the meantime so it does not break anyone's projects.

**Comment by Avindr** [comment]
This has now been implemented. Event naming modules can be used to for event names on EventDefinition assets now instead of pre-processed anim data. 

The slot for AnimData can still be used so as to not break projects but has been marked as legacy and should not be used if possible. The AnimData slot will be hidden when an Event Naming Module is added.
