### ISSUE TITLE
Ability to change speed of clip at runtime

### ISSUE THREAD

**Issue by Westerveld** [Avindr/MxM-IssueTracking#57]
Use Case:
In our game, we want the player to have a reduced speed animation clip when they are low/out of stamina. This would require changing the speed of the clip at runtime.

**Comment by Avindr** [comment]
It is difficult to rationalise clips at runtime since any could play at any given time. I would have to setup a completely new animation clip group setup. I think that the User tags system can be used to achieve this without adding more unnecessary data and complexity into the base system.

To achieve this, simply create a user tag and call it something like "SlowTired" for example:
![image](https://user-images.githubusercontent.com/29056263/91795191-5bd62d80-ec60-11ea-9c3c-31dd71535c38.png)

Tag up all your clips that you want to be affected by your slow tired. 

At runtime you simply need to query this tag and if it is present, modify the speed of the MxMAnimator. If it's not present, set it back to what it should be. 


```
//Cache this value for performance
EUserTags SlowTiredTagHandle = m_mxmAnimator.CurrentAnimData.UserTagFromName("SlowTired");

if(m_mxmAnimator.QueryUserTags(SlowTiredTagHandle))
{
       m_mxmAnimator.DesiredPlaybackSpeed = MyDefaultSpeed * TirednessMultiplier;  //Whatever your desired speed is
}
else
{
       m_mxmAnimator.DesiredPlaybackSpeed = MyDefaultSpeed; //Whatever your standard speed is.
}

```


You can apply your own logic to this concept in any way you like.

Anyway, I'm very hesitant to implement a dedicated system here because it seems relatively game specific which is what User tags were designed for.

I will however, implement a playback speed multiplier which can be modified instead so that any changes you make here do not interfere with by other systems such as Strider or the Event system (when time adjusting)

**Comment by Avindr** [comment]
`public float UserPlaybackSpeedMultiplier { get; set; }`

This has been added in v2.2.6 as an independent speed multiplier to the playback speed. This will be untouched by other systems (i.e. events or strider) and will be a modifier to the base playback speed of the system.

Simply change this value (defaults to 1) when querying the user tags as described in the above post and it should do the same thing without the risk of interference.
